version: "3.8"
services:
  tienda-frontend:
    build:
      context: ./apps/tienda-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/tienda-frontend:/app
      - /app/node_modules
